### ISSUE TITLE
Title doesnt show in color when using Chat

### ISSUE THREAD

**Issue by CherryyColaa** [TubYoub/StatusPlugin#1]
Hi,

When i set a stauts with a color for example &3Hamster it shows the Status correct in the Tab Menu, so it works fine there.
When i use the Chat it shows [&3Hamster]SkeptischHamster: [Message] 
I think it should be colored in chat aswell so maybe there is something that doesnt work like it should

![image](https://github.com/TubYoub/StatusPlugin/assets/36815629/d4d39287-d85f-4cec-a82a-2b9ab08590c3)
![image](https://github.com/TubYoub/StatusPlugin/assets/36815629/a6d73fb6-1c4c-4842-863b-bcc0c10e972f)

ty for help

**Comment by TubYoub** [comment]
Works now with Version 1.3.1 
ty for reporting
