### ISSUE TITLE
Remove empty brackets for no set status

### ISSUE THREAD

**Issue by yukaiin** [TubYoub/StatusPlugin#7]
First of all thanks for creating. Awesome Plugin!

Title basically says everything. When using the Chat function the Brackets are shown even when you have no status set.
This means you get something like "[ ]Username: Message" for a player with no status.
Also I realized that the color feature doesn't work for players without op, but thats probably caused by essentials. Will have to look into that.

**Comment by TubYoub** [comment]
thanks for the feedback,
i will have a look into the bracket issue and your second issue will probably be fixed by giving your playersd the needed permissions using something like LuckPermsor other permission plugins.

**Comment by yukaiin** [comment]
Found the Issue for the name color. In the plugin.yml the permission for name color and stuff is op as default. Editing that in the jar file fixes it. 
For the other thing it's probably in the broadcasting part of the stuff. Idk about coding but in the ChatListener.java you have this part

`            if (status == null) {
                broadcastMessage = player.getName() + ": " + message;
            } else {
                broadcastMessage = "[" + ColourUtils.format(status) + ChatColor.RESET + "] " + player.getName() + ": " + message;
            }`

and I'm pretty sure the else should be a line down. Never programmed in java tho so idk if this will fix it
